### ISSUE TITLE
Kusama Guide not Updating

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2596]

**Comment by salmad3** [comment]
@jakehemmerle 
```
2021-09-17 03:42:20 (28.4 MB/s) - ‘ipfs-cluster-ctl_v0.14.0_linux-amd64.tar.gz’ saved [11802521/11802521]

/home/runner/work/polkadot-wiki/polkadot-wiki/ipfs-cluster-ctl/ipfs-cluster-ctl
2021-09-17T03:42:21.798Z	ERROR	apiclient	client/lbclient.go:105	reached maximum number of retries without success, retries: 1
(node:1946) UnhandledPromiseRejectionWarning: Error: Command failed: ipfs-cluster-ctl     --enc json     --basic-auth ***:***     --host /dns4/hemmerle.dev/tcp/9097/p2p/12D3KooWBxH7hKkvvp2oCDay9jSh8gw5FkdBsdgPytXFjRgqDvf8     status
2021-09-17T03:42:21.798Z	ERROR	apiclient	client/lbclient.go:105	reached maximum number of retries without success, retries: 1

    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at runCommandOnCluster (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:30:50)
    at getCidByPinName (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:40:35)
    at main (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:46:25)
    at Object.<anonymous> (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:62:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by salmad3** [comment]
Fixed with: https://github.com/w3f/polkadot-wiki/commit/88ab66146d28a5311b08fda62bb008a26ea9cee7
IPFS setup WIP:)
