### ISSUE TITLE
Kusama Guide Revamp

### ISSUE THREAD

**Issue by salmad3** [w3f/polkadot-wiki#2597]
https://github.com/w3f/polkadot-wiki/issues/1919#issuecomment-905867464

Issue will now focus on revamping the Kusama guide in general.

**Comment by DannyS03** [comment]
@jakehemmerle 
```
2021-09-17 03:42:20 (28.4 MB/s) - ‘ipfs-cluster-ctl_v0.14.0_linux-amd64.tar.gz’ saved [11802521/11802521]

/home/runner/work/polkadot-wiki/polkadot-wiki/ipfs-cluster-ctl/ipfs-cluster-ctl
2021-09-17T03:42:21.798Z	ERROR	apiclient	client/lbclient.go:105	reached maximum number of retries without success, retries: 1
(node:1946) UnhandledPromiseRejectionWarning: Error: Command failed: ipfs-cluster-ctl     --enc json     --basic-auth ***:***     --host /dns4/hemmerle.dev/tcp/9097/p2p/12D3KooWBxH7hKkvvp2oCDay9jSh8gw5FkdBsdgPytXFjRgqDvf8     status
2021-09-17T03:42:21.798Z	ERROR	apiclient	client/lbclient.go:105	reached maximum number of retries without success, retries: 1

    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at runCommandOnCluster (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:30:50)
    at getCidByPinName (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:40:35)
    at main (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:46:25)
    at Object.<anonymous> (/home/runner/work/polkadot-wiki/polkadot-wiki/scripts/ipfs-cluster-pin.js:62:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by salmad3** [comment]
Main page updated but will benefit from some touch ups.
### Before:
![image](https://user-images.githubusercontent.com/25497083/134516060-5b0d2149-e701-4871-a35e-0760ba5999f4.png)

![image](https://user-images.githubusercontent.com/25497083/134516117-9a08dea9-cb67-4b65-82dd-a7656a716edf.png)

![image](https://user-images.githubusercontent.com/25497083/134516155-cb4accfd-6950-46bd-a1de-cec4183d8246.png)

![image](https://user-images.githubusercontent.com/25497083/134516200-e0fd697a-95c6-4163-bc48-e60ae02a99d1.png)

### Now: https://guide.kusama.network/
